server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dev_nanuid}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update # 개발: update / 운영: validate or none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true

  jwt: # spring: 아래가 아닌 최상위 레벨로 이동
    secret: "xjS8V2k9P4m7tQ3wL6nR1cY5uA2zE8hB4dG9fM3vN7kX"  # 최소 32바이트 이상의 복잡한 키
    access-exp: 3600  # kebab-case로 변경
    refresh-exp: 7200  # kebab-case로 변경
    header: "Authorization"
    prefix: "Bearer"

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
recaptcha:
  secret-key: ${GOOGLE_GCP_SECRET_KEY}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
